[build]
  command = "CI=false yarn build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.20.2"
  GO_VERSION = "none"
  PYTHON_VERSION = "3.9"
  RUBY_VERSION = "none"
  PHP_VERSION = "none"