[build]
  command = "yarn install && CI=false yarn build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.20.2"
  SKIP_PYTHON_SETUP = "true"
  PYTHON_VERSION = ""

[build.processing]
  skip_processing = true